In [ ]:
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Bidirectional,Activation
from keras import optimizers


In [ ]:
 
# 1. 데이터
input_string="hihellohekekehihello"
char_set=sorted(set(input_string))
encoder={k:v for v,k in enumerate(char_set)}
decoder={v:k for v,k in enumerate(char_set)}
print('# Encoder')
print(encoder)
encoded_string= [encoder[c] for c in input_string ]

print('# Encoded string')
print(encoded_string)

string_width=len(input_string)
input_w=4
output_w=string_width-input_w

x=[]
y=[]
for i in range(output_w):
  x.append( encoded_string[i:i+input_w]  )
  y.append( encoded_string[input_w+i]    )

x=array(x)
y=array(y)
x = x.reshape((x.shape[0], x.shape[1], 1))
print(x,y)


# Encoder
{'e': 0, 'h': 1, 'i': 2, 'k': 3, 'l': 4, 'o': 5}
# Encoded string
[1, 2, 1, 0, 4, 4, 5, 1, 0, 3, 0, 3, 0, 1, 2, 1, 0, 4, 4, 5]
[[[1]
  [2]
  [1]
  [0]]

 [[2]
  [1]
  [0]
  [4]]

 [[1]
  [0]
  [4]
  [4]]

 [[0]
  [4]
  [4]
  [5]]

 [[4]
  [4]
  [5]
  [1]]

 [[4]
  [5]
  [1]
  [0]]

 [[5]
  [1]
  [0]
  [3]]

 [[1]
  [0]
  [3]
  [0]]

 [[0]
  [3]
  [0]
  [3]]

 [[3]
  [0]
  [3]
  [0]]

 [[0]
  [3]
  [0]
  [1]]

 [[3]
  [0]
  [1]
  [2]]

 [[0]
  [1]
  [2]
  [1]]

 [[1]
  [2]
  [1]
  [0]]

 [[2]
  [1]
  [0]
  [4]]

 [[1]
  [0]
  [4]
  [4]]] [4 4 5 1 0 3 0 3 0 1 2 1 0 4 4 5]


In [ ]:
 
# 2. 모델 구성
model = Sequential()
model.add(LSTM(10, activation = 'relu', input_shape=(input_w,1)))
# DENSE와 사용법 동일하나 input_shape=(열, 몇개씩잘라작업)
model.add(Dense(5))
model.add(Dense(1))
# model.add(Activation('softmax'))
model.summary()
 

In [ ]:

# 3. 실행
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=100, batch_size=1)

Epoch 1/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 2/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 4/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 5/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 6/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 7/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 8/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 9/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 10/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 11/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 12/100
16/16 [==============================] - 0s 2ms/step - loss: 5.0625
Epoch 13/100
16/16 [=================

In [ ]:
test_string="hihe"
x_input = array([encoder[c] for c in test_string ] )
x_input = x_input.reshape((1,input_w,1))
print(f"# test string\n {test_string}")



yhat = model.predict(x_input)
out=decoder[round(yhat[0][0])]
print(f"# test output\n {out}")

# test string
 hihe
# test output
 h
