In [1]:
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM




# 1. Data


In [2]:
input_string="hihello"
char_set=sorted(set(input_string))
encoder={k:v for v,k in enumerate(char_set)}
decoder={v:k for v,k in enumerate(char_set)}
print('# Encoder')
print(encoder)
encoded_string= [encoder[c] for c in input_string ]

print('# Encoded string')
print(encoded_string)

string_width=len(input_string)
input_w=4
output_w=string_width-input_w

x=[]
y=[]
for i in range(output_w):
 x.append( encoded_string[i:i+input_w]  )
 y.append( encoded_string[input_w+i]    )

x=array(x)
y=array(y)
x = x.reshape((x.shape[0], x.shape[1], 1))
print(x,y)




# Encoder
{'e': 0, 'h': 1, 'i': 2, 'l': 3, 'o': 4}
# Encoded string
[1, 2, 1, 0, 3, 3, 4]
[[[1]
  [2]
  [1]
  [0]]

 [[2]
  [1]
  [0]
  [3]]

 [[1]
  [0]
  [3]
  [3]]] [3 3 4]


# 2. Keras Model


In [3]:
model = Sequential()
model.add(LSTM(10, activation = 'relu', input_shape=(input_w,1)))
# DENSE와 사용법 동일하나 input_shape=(열, 몇개씩잘라작업)
model.add(Dense(5))
model.add(Dense(1))

model.summary()




Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm (LSTM)                  (None, 10)                480       
_________________________________________________________________
dense (Dense)                (None, 5)                 55        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 6         
Total params: 541
Trainable params: 541
Non-trainable params: 0
_________________________________________________________________


# 3. Training


In [4]:
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=100, batch_size=1)



Epoch 1/100
3/3 [==============================] - 0s 3ms/step - loss: 9.1631
Epoch 2/100
3/3 [==============================] - 0s 3ms/step - loss: 9.0030
Epoch 3/100
3/3 [==============================] - 0s 2ms/step - loss: 8.8337
Epoch 4/100
3/3 [==============================] - 0s 3ms/step - loss: 8.6528
Epoch 5/100
3/3 [==============================] - 0s 2ms/step - loss: 8.4873
Epoch 6/100
3/3 [==============================] - 0s 3ms/step - loss: 8.2908
Epoch 7/100
3/3 [==============================] - 0s 3ms/step - loss: 8.1225
Epoch 8/100
3/3 [==============================] - 0s 2ms/step - loss: 7.9279
Epoch 9/100
3/3 [==============================] - 0s 3ms/step - loss: 7.7461
Epoch 10/100
3/3 [==============================] - 0s 2ms/step - loss: 7.5473
Epoch 11/100
3/3 [==============================] - 0s 3ms/step - loss: 7.3132
Epoch 12/100
3/3 [==============================] - 0s 3ms/step - loss: 7.1360
Epoch 13/100
3/3 [==============================] - 0s 2ms/st

# 4.Test


In [5]:
test_string="hihe"
x_input = array([encoder[c] for c in test_string ] )
x_input = x_input.reshape((1,input_w,1))
print(f"# test string\n {test_string}")
yhat = model.predict(x_input)
out=decoder[round(yhat[0][0])]
print(f"# test output\n {out}")


# test string
 hihe
# test output
 l
