In [1]:
from numpy import array
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, SimpleRNN


# 1. Data
input_string="hihello"
char_set=sorted(set(input_string))
encoder={k:v for v,k in enumerate(char_set)}
decoder={v:k for v,k in enumerate(char_set)}
print('# Encoder')
print(encoder)
encoded_string= [encoder[c] for c in input_string ]

print('# Encoded string')
print(encoded_string)

string_width=len(input_string)
input_w=4
output_w=string_width-input_w

x=[]
y=[]
for i in range(output_w):
 x.append( encoded_string[i:i+input_w]  )
 y.append( encoded_string[input_w+i]    )

x=array(x)
y=array(y)
x = x.reshape((x.shape[0], x.shape[1], 1))
print(x,y)


# 2. Keras Model
model = Sequential()
# model.add(LSTM(10, activation = 'relu', input_shape=(input_w,1)))
model.add(SimpleRNN(10, activation = 'relu', input_shape=(input_w,1)))

# DENSE와 사용법 동일하나 input_shape=(열, 몇개씩잘라작업)
model.add(Dense(5))
model.add(Dense(1))

model.summary()


# 3. Training
model.compile(optimizer='adam', loss='mse')
model.fit(x, y, epochs=100, batch_size=1)

# 4.Test
test_string="hihe"
x_input = array([encoder[c] for c in test_string ] )
x_input = x_input.reshape((1,input_w,1))
print(f"# test string\n {test_string}")
yhat = model.predict(x_input)
out=decoder[round(yhat[0][0])]
print(f"# test output\n {out}")


# Encoder
{'e': 0, 'h': 1, 'i': 2, 'l': 3, 'o': 4}
# Encoded string
[1, 2, 1, 0, 3, 3, 4]
[[[1]
  [2]
  [1]
  [0]]

 [[2]
  [1]
  [0]
  [3]]

 [[1]
  [0]
  [3]
  [3]]] [3 3 4]
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 10)                120       
_________________________________________________________________
dense (Dense)                (None, 5)                 55        
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 6         
Total params: 181
Trainable params: 181
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
3/3 [==============================] - 0s 3ms/step - loss: 10.5463
Epoch 2/100
3/3 [==============================] - 0s 2ms/step - loss: 9.8005
Epoch 3/100
3/3 [==============================] - 0s 2